### ISSUE TITLE
Architecture of Resnet50

### ISSUE THREAD

**Issue by SiwarBG-2019** [moyiliyi/keras-faster-rcnn#1]
The architecture of resnet50 built in the file resnet.py seems incorrect. I think your resnet-50 model is missing what is called **stage 5** consisting of a convolutional block followed by 2 identity blocks. 

I'm looking for explanations. thank you in advance

**Comment by moyiliyi** [comment]
Hello SiwarBG,
The stage 5 is used as the classifier_layers, after the ROI pooling.
